/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-02-12 at 03:38:18 UTC 
 * Modify at your own risk.
 */

package com.example.supertest.signupendpoint.model;

/**
 * Model definition for SignUp.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the signupendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SignUp extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime checkinDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nric;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer phone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userEmail;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCheckinDate() {
    return checkinDate;
  }

  /**
   * @param checkinDate checkinDate or {@code null} for none
   */
  public SignUp setCheckinDate(com.google.api.client.util.DateTime checkinDate) {
    this.checkinDate = checkinDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public SignUp setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNric() {
    return nric;
  }

  /**
   * @param nric nric or {@code null} for none
   */
  public SignUp setNric(java.lang.String nric) {
    this.nric = nric;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPhone() {
    return phone;
  }

  /**
   * @param phone phone or {@code null} for none
   */
  public SignUp setPhone(java.lang.Integer phone) {
    this.phone = phone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPin() {
    return pin;
  }

  /**
   * @param pin pin or {@code null} for none
   */
  public SignUp setPin(java.lang.String pin) {
    this.pin = pin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserEmail() {
    return userEmail;
  }

  /**
   * @param userEmail userEmail or {@code null} for none
   */
  public SignUp setUserEmail(java.lang.String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  @Override
  public SignUp set(String fieldName, Object value) {
    return (SignUp) super.set(fieldName, value);
  }

  @Override
  public SignUp clone() {
    return (SignUp) super.clone();
  }

}
