/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-02-12 at 03:38:18 UTC 
 * Modify at your own risk.
 */

package com.example.supertest.signupendpoint;

/**
 * Service definition for Signupendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SignupendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Signupendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the signupendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "signupendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Signupendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Signupendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getSignUp".
   *
   * This request holds the parameters needed by the the signupendpoint server.  After setting any
   * optional parameters, call the {@link GetSignUp#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetSignUp getSignUp(java.lang.Long id) throws java.io.IOException {
    GetSignUp result = new GetSignUp(id);
    initialize(result);
    return result;
  }

  public class GetSignUp extends SignupendpointRequest<com.example.supertest.signupendpoint.model.SignUp> {

    private static final String REST_PATH = "signup/{id}";

    /**
     * Create a request for the method "getSignUp".
     *
     * This request holds the parameters needed by the the signupendpoint server.  After setting any
     * optional parameters, call the {@link GetSignUp#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetSignUp#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetSignUp(java.lang.Long id) {
      super(Signupendpoint.this, "GET", REST_PATH, null, com.example.supertest.signupendpoint.model.SignUp.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSignUp setAlt(java.lang.String alt) {
      return (GetSignUp) super.setAlt(alt);
    }

    @Override
    public GetSignUp setFields(java.lang.String fields) {
      return (GetSignUp) super.setFields(fields);
    }

    @Override
    public GetSignUp setKey(java.lang.String key) {
      return (GetSignUp) super.setKey(key);
    }

    @Override
    public GetSignUp setOauthToken(java.lang.String oauthToken) {
      return (GetSignUp) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSignUp setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSignUp) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSignUp setQuotaUser(java.lang.String quotaUser) {
      return (GetSignUp) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSignUp setUserIp(java.lang.String userIp) {
      return (GetSignUp) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetSignUp setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetSignUp set(String parameterName, Object value) {
      return (GetSignUp) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertSignUp".
   *
   * This request holds the parameters needed by the the signupendpoint server.  After setting any
   * optional parameters, call the {@link InsertSignUp#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.supertest.signupendpoint.model.SignUp}
   * @return the request
   */
  public InsertSignUp insertSignUp(com.example.supertest.signupendpoint.model.SignUp content) throws java.io.IOException {
    InsertSignUp result = new InsertSignUp(content);
    initialize(result);
    return result;
  }

  public class InsertSignUp extends SignupendpointRequest<com.example.supertest.signupendpoint.model.SignUp> {

    private static final String REST_PATH = "signup";

    /**
     * Create a request for the method "insertSignUp".
     *
     * This request holds the parameters needed by the the signupendpoint server.  After setting any
     * optional parameters, call the {@link InsertSignUp#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertSignUp#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.supertest.signupendpoint.model.SignUp}
     * @since 1.13
     */
    protected InsertSignUp(com.example.supertest.signupendpoint.model.SignUp content) {
      super(Signupendpoint.this, "POST", REST_PATH, content, com.example.supertest.signupendpoint.model.SignUp.class);
    }

    @Override
    public InsertSignUp setAlt(java.lang.String alt) {
      return (InsertSignUp) super.setAlt(alt);
    }

    @Override
    public InsertSignUp setFields(java.lang.String fields) {
      return (InsertSignUp) super.setFields(fields);
    }

    @Override
    public InsertSignUp setKey(java.lang.String key) {
      return (InsertSignUp) super.setKey(key);
    }

    @Override
    public InsertSignUp setOauthToken(java.lang.String oauthToken) {
      return (InsertSignUp) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertSignUp setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertSignUp) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertSignUp setQuotaUser(java.lang.String quotaUser) {
      return (InsertSignUp) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertSignUp setUserIp(java.lang.String userIp) {
      return (InsertSignUp) super.setUserIp(userIp);
    }

    @Override
    public InsertSignUp set(String parameterName, Object value) {
      return (InsertSignUp) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listSignUp".
   *
   * This request holds the parameters needed by the the signupendpoint server.  After setting any
   * optional parameters, call the {@link ListSignUp#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListSignUp listSignUp() throws java.io.IOException {
    ListSignUp result = new ListSignUp();
    initialize(result);
    return result;
  }

  public class ListSignUp extends SignupendpointRequest<com.example.supertest.signupendpoint.model.CollectionResponseSignUp> {

    private static final String REST_PATH = "signup";

    /**
     * Create a request for the method "listSignUp".
     *
     * This request holds the parameters needed by the the signupendpoint server.  After setting any
     * optional parameters, call the {@link ListSignUp#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListSignUp#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListSignUp() {
      super(Signupendpoint.this, "GET", REST_PATH, null, com.example.supertest.signupendpoint.model.CollectionResponseSignUp.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListSignUp setAlt(java.lang.String alt) {
      return (ListSignUp) super.setAlt(alt);
    }

    @Override
    public ListSignUp setFields(java.lang.String fields) {
      return (ListSignUp) super.setFields(fields);
    }

    @Override
    public ListSignUp setKey(java.lang.String key) {
      return (ListSignUp) super.setKey(key);
    }

    @Override
    public ListSignUp setOauthToken(java.lang.String oauthToken) {
      return (ListSignUp) super.setOauthToken(oauthToken);
    }

    @Override
    public ListSignUp setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListSignUp) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListSignUp setQuotaUser(java.lang.String quotaUser) {
      return (ListSignUp) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListSignUp setUserIp(java.lang.String userIp) {
      return (ListSignUp) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListSignUp setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListSignUp setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListSignUp set(String parameterName, Object value) {
      return (ListSignUp) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeSignUp".
   *
   * This request holds the parameters needed by the the signupendpoint server.  After setting any
   * optional parameters, call the {@link RemoveSignUp#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveSignUp removeSignUp(java.lang.Long id) throws java.io.IOException {
    RemoveSignUp result = new RemoveSignUp(id);
    initialize(result);
    return result;
  }

  public class RemoveSignUp extends SignupendpointRequest<Void> {

    private static final String REST_PATH = "signup/{id}";

    /**
     * Create a request for the method "removeSignUp".
     *
     * This request holds the parameters needed by the the signupendpoint server.  After setting any
     * optional parameters, call the {@link RemoveSignUp#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveSignUp#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveSignUp(java.lang.Long id) {
      super(Signupendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveSignUp setAlt(java.lang.String alt) {
      return (RemoveSignUp) super.setAlt(alt);
    }

    @Override
    public RemoveSignUp setFields(java.lang.String fields) {
      return (RemoveSignUp) super.setFields(fields);
    }

    @Override
    public RemoveSignUp setKey(java.lang.String key) {
      return (RemoveSignUp) super.setKey(key);
    }

    @Override
    public RemoveSignUp setOauthToken(java.lang.String oauthToken) {
      return (RemoveSignUp) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveSignUp setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveSignUp) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveSignUp setQuotaUser(java.lang.String quotaUser) {
      return (RemoveSignUp) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveSignUp setUserIp(java.lang.String userIp) {
      return (RemoveSignUp) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveSignUp setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveSignUp set(String parameterName, Object value) {
      return (RemoveSignUp) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateSignUp".
   *
   * This request holds the parameters needed by the the signupendpoint server.  After setting any
   * optional parameters, call the {@link UpdateSignUp#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.supertest.signupendpoint.model.SignUp}
   * @return the request
   */
  public UpdateSignUp updateSignUp(com.example.supertest.signupendpoint.model.SignUp content) throws java.io.IOException {
    UpdateSignUp result = new UpdateSignUp(content);
    initialize(result);
    return result;
  }

  public class UpdateSignUp extends SignupendpointRequest<com.example.supertest.signupendpoint.model.SignUp> {

    private static final String REST_PATH = "signup";

    /**
     * Create a request for the method "updateSignUp".
     *
     * This request holds the parameters needed by the the signupendpoint server.  After setting any
     * optional parameters, call the {@link UpdateSignUp#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateSignUp#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.supertest.signupendpoint.model.SignUp}
     * @since 1.13
     */
    protected UpdateSignUp(com.example.supertest.signupendpoint.model.SignUp content) {
      super(Signupendpoint.this, "PUT", REST_PATH, content, com.example.supertest.signupendpoint.model.SignUp.class);
    }

    @Override
    public UpdateSignUp setAlt(java.lang.String alt) {
      return (UpdateSignUp) super.setAlt(alt);
    }

    @Override
    public UpdateSignUp setFields(java.lang.String fields) {
      return (UpdateSignUp) super.setFields(fields);
    }

    @Override
    public UpdateSignUp setKey(java.lang.String key) {
      return (UpdateSignUp) super.setKey(key);
    }

    @Override
    public UpdateSignUp setOauthToken(java.lang.String oauthToken) {
      return (UpdateSignUp) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSignUp setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSignUp) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSignUp setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSignUp) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSignUp setUserIp(java.lang.String userIp) {
      return (UpdateSignUp) super.setUserIp(userIp);
    }

    @Override
    public UpdateSignUp set(String parameterName, Object value) {
      return (UpdateSignUp) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Signupendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Signupendpoint}. */
    @Override
    public Signupendpoint build() {
      return new Signupendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SignupendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSignupendpointRequestInitializer(
        SignupendpointRequestInitializer signupendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(signupendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
